export const CountryCodes = [
    { country: 'United States', code: '+1', flag: '🇺🇸' },
    { country: 'India', code: '+91', flag: '🇮🇳' },
    { country: 'United Arab Emirates', code: '+971', flag: '🇦🇪' },
    { country: 'United Kingdom', code: '+44', flag: '🇬🇧' },
    { country: 'Canada', code: '+1', flag: '🇨🇦' },
    { country: 'Australia', code: '+61', flag: '🇦🇺' },
    { country: 'Germany', code: '+49', flag: '🇩🇪' },
    { country: 'France', code: '+33', flag: '🇫🇷' },
    { country: 'Pakistan', code: '+92', flag: '🇵🇰' },
    { country: 'Saudi Arabia', code: '+966', flag: '🇸🇦' },
    { country: 'Qatar', code: '+974', flag: '🇶🇦' },
    { country: 'Oman', code: '+968', flag: '🇴🇲' },
    { country: 'Kuwait', code: '+965', flag: '🇰🇼' },
    { country: 'Bahrain', code: '+973', flag: '🇧🇭' },
    { country: 'Egypt', code: '+20', flag: '🇪🇬' },
    { country: 'Bangladesh', code: '+880', flag: '🇧🇩' },
    { country: 'Nepal', code: '+977', flag: '🇳🇵' },
    { country: 'Sri Lanka', code: '+94', flag: '🇱🇰' },
    { country: 'South Africa', code: '+27', flag: '🇿🇦' },
    { country: 'Philippines', code: '+63', flag: '🇵🇭' },
    { country: 'Indonesia', code: '+62', flag: '🇮🇩' },
    { country: 'Malaysia', code: '+60', flag: '🇲🇾' },
    { country: 'Turkey', code: '+90', flag: '🇹🇷' },
    { country: 'Nigeria', code: '+234', flag: '🇳🇬' },
    { country: 'Brazil', code: '+55', flag: '🇧🇷' },
  ];
  