export const constant = {
  Login: "Login",
  SignUp: "Register",
  ForgetPassword:"forget_password",
  OtpVerify:"otpVerify",
  UpdatePassword:"UpdatePassword",
  changePassword:"change-password",
  getrofile:"get-profile",
  getPrivacy:"get-privacy-policy",
  getAboutUs:"get-about-us",
  updateProfile:"update-profile",
  Addfeedback:"add_feedback",
   getPosition:"get_position",
   getCategory:"get_category",
  getBanner:"get_banner",
  getPostcity:"get_post_city",
  getallServices:"getallCategory",
  togglePostSave:"togglePostSave",
  getServicesByCategory:"getServicesByCategory",
  getServiceById:"getServiceById",
  get_package:"get_package",
  getServicesByCity:"getServicesByCity",
  addServiceWithTime:"addServiceWithTime",
   addSellerDocument:"add_seller_document",
  getServicesBySeller:"getServicesBySeller",
  get_seller_document:"get_seller_document",
  update_seller_document:"update_seller_document",
  delete_seller_documents:"delete_seller_documents",
  getServicesBySellerAndCategory:"getServicesBySellerAndCategory",
   editSellerVendorActivity: "editSellerVendorActivity",
  deleteSellerVendorActivity:"deleteSellerVendorActivity",
  addSellerVendorActivity:'addSellerVendorActivity',
  addSellerCategory:"add_seller_category",
  getActivites:"get_activites",
  addSubActivity:'addSubActivity',
  getHotels :"get_hotels",
   Getfaq:"get_faq",
  AddContact_us:"add_contact_us",
  updateOrInsertTimeByDay:"updateOrInsertTimeByDay",
  book_service:"book_service",
  get_booking_list:"get_booking_list",
  update_booking_status:"update_booking_status",
  user_bookings_with_services:"get_user_bookings_with_services",
  get_seller_count_list:"get_seller_count_list",
  add_rates:"add_rates" ,
  user_booking_cancel:"user_booking_cancel",
  app_launch_paywall:"app_launch_paywall",
  deleteImageFromServiceGallery:"deleteImageFromServiceGallery",
  addImageToServiceGallery:"addImageToServiceGallery",
  getTransactionsByOwner:"getTransactionsByOwner",
  requestPayment:"requestPayment"
};
export const base_url = 'https://server-php-8-3.technorizen.com/Inside/api/';
export const image_url = 'https://server-php-8-3.technorizen.com/Inside/api/';

